name: Click Wakeup Button

on:
  schedule:
    - cron: '0 */4 * * *'  # 4시간마다 실행
  workflow_dispatch:

jobs:
  click_button:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Puppeteer
        run: |
          npm init -y
          npm install puppeteer

      - name: Run Puppeteer Script
        run: node click_button.js
