# .github/workflows/wake-streamlit.yml

name: Wake Streamlit App

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  wake_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install puppeteer

      - name: Run puppeteer script
        run: |
          node wakeup.js

      - name: Show result
        run: echo "Wake up sequence completed."

      - name: Debug URL
        run: curl -I https://testforcal.streamlit.app
