name: Keep Streamlit Alive

on:
  schedule:
    - cron: '0 */4 * * *'  # 매일 4시간마다 UTC 기준 실행
  workflow_dispatch:

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Curl the Streamlit app
        run: |
          curl -s -o /dev/null -w "%{http_code}\n" https://calendarforpar.streamlit.app
