name: Keep Streamlit Alive

on:
  schedule:
    - cron: '0 6 * * *'  # 매일 UTC 오전 6시
  workflow_dispatch:

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Curl the Streamlit app
        run: |
          curl -s -o /dev/null -w "%{http_code}\n" https://calendarforpar.streamlit.app
