# .github/workflows/keep-streamlit-alive.yml

name: Keep Streamlit Alive

on:
  schedule:
    - cron: '0 */4 * * *'  # 매 4시간마다 UTC 기준
  workflow_dispatch:

jobs:
  keep_alive:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Keep Streamlit app alive
        run: |
          python keep_alive.py
